# FFmpeg configuration
ffmpeg_config:
  # General settings
  timeout: 10  # seconds
  retries: 5
  retry_delay: 1.0  # seconds between retries
  
  # Frame extraction settings
  frame_extraction:
    default_fps: "1/5"  # frames per second
    format: "png"
    quality: 100  # 1-100
    
  # Audio settings
  audio:
    preferred_format: "flac"
    compression_level: 8
    mixing:
      default_volumes: [0.10, 0.90]  # Default volume levels for mixing

  # File handling
  compatible_formats:
    video: [".mp4", ".mov", ".avi", ".mkv"]
    audio: [".wav", ".mp3", ".aac", ".flac", ".m4a"]